// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjqqK4bzmbwet6M5Z34bnENLM8btXcjX8',
    appId: '1:1082186508937:web:5d00bbe1687c976d5db458',
    messagingSenderId: '1082186508937',
    projectId: 'quizapp-11a7c',
    authDomain: 'quizapp-11a7c.firebaseapp.com',
    storageBucket: 'quizapp-11a7c.appspot.com',
    measurementId: 'G-B11PBY0TKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP85L3eaxqbZ96n4bHu9r20Vi2uzRi3xk',
    appId: '1:1082186508937:android:825a37e3b4e429ca5db458',
    messagingSenderId: '1082186508937',
    projectId: 'quizapp-11a7c',
    storageBucket: 'quizapp-11a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUG2pcBtdP0hnsUbSf1PsQYRxCS3gLpmI',
    appId: '1:1082186508937:ios:ea7211463309f1515db458',
    messagingSenderId: '1082186508937',
    projectId: 'quizapp-11a7c',
    storageBucket: 'quizapp-11a7c.appspot.com',
    iosBundleId: 'com.example.laptopPasal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUG2pcBtdP0hnsUbSf1PsQYRxCS3gLpmI',
    appId: '1:1082186508937:ios:ea7211463309f1515db458',
    messagingSenderId: '1082186508937',
    projectId: 'quizapp-11a7c',
    storageBucket: 'quizapp-11a7c.appspot.com',
    iosBundleId: 'com.example.laptopPasal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjqqK4bzmbwet6M5Z34bnENLM8btXcjX8',
    appId: '1:1082186508937:web:4169ccd648457bbc5db458',
    messagingSenderId: '1082186508937',
    projectId: 'quizapp-11a7c',
    authDomain: 'quizapp-11a7c.firebaseapp.com',
    storageBucket: 'quizapp-11a7c.appspot.com',
    measurementId: 'G-6QSCS7D7BY',
  );
}
